/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemarodoviario.tela;

/**
 *
 * @author rafae
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(this);
    }
    
    private static menu instancia = null;
    /**
     * Creates new form TelaCadAluno
     */

    public static menu getInstancia() {
        if (instancia == null)
            instancia = new menu();
        
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btVeiculo = new javax.swing.JButton();
        btFaturas = new javax.swing.JButton();
        btRoteiros = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btPassagens = new javax.swing.JButton();
        btCidade2 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Rodoviário");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setName(""); // NOI18N

        btVeiculo.setBackground(new java.awt.Color(102, 204, 255));
        btVeiculo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btVeiculo.setText("Veículo");
        btVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVeiculo.setMaximumSize(new java.awt.Dimension(93, 23));
        btVeiculo.setMinimumSize(new java.awt.Dimension(93, 23));
        btVeiculo.setPreferredSize(new java.awt.Dimension(93, 23));
        btVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeiculoActionPerformed(evt);
            }
        });

        btFaturas.setBackground(new java.awt.Color(102, 204, 255));
        btFaturas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFaturas.setText("Faturas");
        btFaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFaturasActionPerformed(evt);
            }
        });

        btRoteiros.setBackground(new java.awt.Color(102, 204, 255));
        btRoteiros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRoteiros.setText("Roteiros");
        btRoteiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRoteirosActionPerformed(evt);
            }
        });

        btUsuario.setBackground(new java.awt.Color(102, 204, 255));
        btUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUsuario.setText("Usuário");
        btUsuario.setFocusable(false);
        btUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafae\\Downloads\\bus.jpg")); // NOI18N

        btPassagens.setBackground(new java.awt.Color(102, 204, 255));
        btPassagens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPassagens.setText("Passagens");
        btPassagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPassagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPassagensActionPerformed(evt);
            }
        });

        btCidade2.setBackground(new java.awt.Color(102, 204, 255));
        btCidade2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCidade2.setText("Cidade");
        btCidade2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btCidade2.setMaximumSize(new java.awt.Dimension(93, 23));
        btCidade2.setMinimumSize(new java.awt.Dimension(93, 23));
        btCidade2.setPreferredSize(new java.awt.Dimension(93, 23));
        btCidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCidade2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btPassagens, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRoteiros, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btRoteiros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPassagens, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeiculoActionPerformed
        // TODO add your handling code here:
        if (!Veiculo.getInstancia().isVisible()) {
            Veiculo.getInstancia().setVisible(true);
        } else {
            Veiculo.getInstancia().requestFocus();
        }
        
    }//GEN-LAST:event_btVeiculoActionPerformed

    private void btPassagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPassagensActionPerformed
        // TODO add your handling code here:
        if (!passagens.getInstancia().isVisible()) {
            passagens.getInstancia().setVisible(true);
        } else {
            passagens.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_btPassagensActionPerformed

    private void btCidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCidade2ActionPerformed
        // TODO add your handling code here:
        if (!cidade.getInstancia().isVisible()) {
            cidade.getInstancia().setVisible(true);
        } else {
            cidade.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_btCidade2ActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        // TODO add your handling code here:
        if (!usuario.getInstancia().isVisible()) {
            usuario.getInstancia().setVisible(true);
        } else {
            usuario.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFaturasActionPerformed
        // TODO add your handling code here:
        if (!Faturas.getInstancia().isVisible()) {
            Faturas.getInstancia().setVisible(true);
        } else {
            Faturas.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_btFaturasActionPerformed

    private void btRoteirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRoteirosActionPerformed
        // TODO add your handling code here:
        if (!roteiros.getInstancia().isVisible()) {
            roteiros.getInstancia().setVisible(true);
        } else {
            roteiros.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_btRoteirosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCidade2;
    private javax.swing.JButton btFaturas;
    private javax.swing.JButton btPassagens;
    private javax.swing.JButton btRoteiros;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
